### ISSUE TITLE
Soory, but How to install

### ISSUE THREAD

**Issue by DaFray31** [Jinya-CMS/Jinya-Gallery-CMS#681]
Hello,
Sorry but I can't install, do you have a procedure to follow ?
Thanks a lot,
Regards,
DaFray31

**Comment by DerKnerd** [comment]
Hey DaFray31,

the installation is fairly easy. You need to grab the most recent version from https://files.jinya.de/cms/stable/ current is 15.0.0 and put the contents of the zip on your webserver and point the domain to the installation directory.

A short side note, Jinya is currently only in German, an English version will be added with version 16.0.0.

Greetings
Knerd

**Comment by DaFray31** [comment]
I put the zip in the web server's folder, except that when I go to the public folder, I get a 500 error (same when I try to access index.php). (on Brave browser, but on Firefox i have blank page)
Also if you want I can help you to translate it into French.

I'm looking forward to hearing from you,
DaFray31

**Comment by DerKnerd** [comment]
You need to extract the zip to the web server folder and point the domain to `{installDir}/public`. That should give you the install wizard when you access it.

And yeah a french translation would be great :)

**Comment by DaFray31** [comment]
Exactly, that's what I do and I always get a 500 error !

**Comment by DerKnerd** [comment]
Which php version are you using? Jinya requires version 7.4.

**Comment by DaFray31** [comment]
Nothing's changed :/
 if you want I can give you access to my host.

**Comment by DaFray31** [comment]
The errors I find in my server logs are :
`Sat Mar 21 20:37:13.692322 2020] [authz_core:error] [pid 21343:tid 47570500544256] [client _ip_] AH01630: client denied by server configuration: /home/jamamamchs/public_html/src/                    `

**Comment by DaFray31** [comment]
Also mt .htaccess is :
```
<IfModule mod_authz_core.c>
    Require all granted
</IfModule>
<IfModule !mod_authz_core.c>
    Order deny,allow
    Allow from all
</IfModule>

```

**Comment by DerKnerd** [comment]
Jinya provides its own .htaccess to set several properties. Maybe that could cause the issue.
